package config

import (
	"encoding/json"
	"reflect"
	"strings"
)

// JSONSchema returns a JSON Schema (draft 2020-12) for the sloppy.yaml File struct,
// generated by reflection so it cannot drift from the struct. `sloppy config schema`
// emits it; the init scaffold points its `# yaml-language-server: $schema=` header at
// the published copy so hand-editors get autocomplete + a field reference.
func JSONSchema() ([]byte, error) {
	s := schemaForType(reflect.TypeOf(File{}))
	s["$schema"] = "https://json-schema.org/draft/2020-12/schema"
	s["title"] = "Sloppy Joe configuration (sloppy.yaml)"
	return json.MarshalIndent(s, "", "  ")
}

func schemaForType(t reflect.Type) map[string]any {
	switch t.Kind() {
	case reflect.String:
		return map[string]any{"type": "string"}
	case reflect.Bool:
		return map[string]any{"type": "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return map[string]any{"type": "integer"}
	case reflect.Float32, reflect.Float64:
		return map[string]any{"type": "number"}
	case reflect.Slice:
		return map[string]any{"type": "array", "items": schemaForType(t.Elem())}
	case reflect.Map:
		return map[string]any{"type": "object", "additionalProperties": schemaForType(t.Elem())}
	case reflect.Struct:
		props := map[string]any{}
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			if !f.IsExported() {
				continue
			}
			name := yamlFieldName(f)
			if name == "" || name == "-" {
				continue // inline maps (recipe params) merge into the parent object
			}
			props[name] = schemaForType(f.Type)
		}
		return map[string]any{"type": "object", "properties": props}
	default: // interface{} and anything else: unconstrained
		return map[string]any{}
	}
}

// yamlFieldName returns the yaml key for a struct field, or "" to skip it (unnamed
// or ,inline). Mirrors how LoadFile decodes the same struct.
func yamlFieldName(f reflect.StructField) string {
	tag := f.Tag.Get("yaml")
	if tag == "" {
		return strings.ToLower(f.Name)
	}
	parts := strings.Split(tag, ",")
	for _, opt := range parts[1:] {
		if opt == "inline" {
			return ""
		}
	}
	return parts[0]
}
